language: node_js
node_js:
- "4"
addons:
  apt:
    packages:
    - cloc
script:
- npm test
- node bin/collect-repos -u lukasmartinelli -o repos.json
- node bin/collect-repo-stats -i repos.json -o repostats.json
