language: node_js
node_js:
- "4"
addons:
  apt:
    packages:
    - cloc
script:
- npm test
- node bin/collect-repos -u manuelroth -o repos.json
- node bin/collect-repo-stats --use-https -i repos.json -o repostats.json
